# Generated by Django 3.2.8 on 2021-11-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('mobile_phone', models.CharField(max_length=30, verbose_name='手机号')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
            ],
        ),
    ]
